name: rikulo_commons
version: 1.0.1+1
description: Common reusable Dart classes and utilities.
authors:
- Tom Yeh <tomyeh@rikulo.org>
- Henri Chen <henrichen@rikulo.org>
- Simon Pai <simonpai@rikulo.org>
homepage: http://rikulo.org
dependencies:
  unittest: any
  logging: any
  mime: any
environment:
  sdk: ">=1.0.0"
